version: "3.9"

services:
  front:
    image: stasy23/front_2:lesson-36
    ports:
      - 8081:81
    depends_on:
      - api
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/app/.env
